### ISSUE TITLE
Can we add twitter to it ? or should i do it ?

### ISSUE THREAD

**Issue by ijameelkhan** [jonasman/JNSocialDownload#2]

**Comment by jonasman** [comment]
Hmm

Twitter is good but the class name mentions facebook.

2 options:
 rename the class and add twitter 
Create a new class and add similar api for twitter

Joao

Enviado do meu iPhone

No dia 19/11/2014, às 02:23, ijameelkhan notifications@github.com escreveu:

**Comment by ijameelkhan** [comment]
Added via 6543718b593e84e6938e5798bbcc27a67b7e2d1f
